### ISSUE TITLE
Backend functions

### ISSUE THREAD

**Issue by Alex7Li** [Alex7Li/WatShines4u#6]
Function headers that I want. The Person object can be modified based on your preferences
```python
def get_matches(desiriratta: str) -> List[Person]:
    """
    Given a string description of someone's dating preferences, this function returns
    a list of ~5 people who might satisfy the preferences.
   Example:
    a = get_matches("I want someone mean")
    a[0] = {name: "Rude man", description: "He beat me up on my date"}
    """
```

```python
def add_review(review: str, person_reviewed: Person) -> void
    """
    Given a review and a person being reviewed, this function adds the review to the database.
   Example:
    add_review("He beat me up on my date", {name:"Rude man"}
    """
```

**Comment by samuelstevens** [comment]
For get_matches, it includes name, description, keywords and categories (categories are for use with yelp). I'll add the add_review function tonight and open a PR.

**Comment by Alex7Li** [comment]
I added these functions to main.py for someone to fill out in PR #11

**Comment by ritachitsark** [comment]
> I added these functions to main.py for someone to fill out in PR #11

For the get_places() function, how do you want the 3 places to be retrieved? Do we send a query over to Yelp before this function call?

**Comment by Alex7Li** [comment]
I was imagining calling the yelp query from within the get_places() function. Is the problem that you don't have the right parameters for that call? If so we can just add it to the function header

**Comment by AnthonyFortuna** [comment]
for get_places() I'm sure we'd just pop the passed string into the query parameter for the yelp api call
